// <auto-generated />
using IplanRio.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IplanRio.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ContextIplanRio))]
    partial class ContextIplanRioModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IplanRio.Domain.Entities.Shopping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnName("Endereco");

                    b.Property<string>("HoraAbertura")
                        .IsRequired()
                        .HasColumnName("HoraAbertura");

                    b.Property<string>("HoraFechamento")
                        .IsRequired()
                        .HasColumnName("HoraFechamento");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnName("Nome");

                    b.HasKey("Id");

                    b.ToTable("Shopping");

                    b.HasData(
                        new { Id = 1, Endereco = "Rua Lauro Müller, 116 - Botafogo, Rio de Janeiro - RJ, 22290-160", HoraAbertura = "10:00", HoraFechamento = "22:00", Nome = "Shopping Rio Sul" },
                        new { Id = 2, Endereco = "Av. Vicente de Carvalho, 909 - Vila da Penha, Rio de Janeiro - RJ, 21210-000", HoraAbertura = "10:00", HoraFechamento = "22:00", Nome = "Shopping Carioca" },
                        new { Id = 3, Endereco = "Av. Maracanã, 987 - Tijuca, Rio de Janeiro - RJ, 20511-000", HoraAbertura = "10:00", HoraFechamento = "22:00", Nome = "Shopping Tijuca" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
